on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Keys__GeminiApi: ${{ secrets.GEMINI_API }}
      Keys__TtsApi: ${{ secrets.TTS_API }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check secrets availability
        run: |
          if [ -z "$Keys__GeminiApi" ] || [ -z "$Keys__TtsApi" ]; then
            echo "One or more secrets are missing!"
            exit 1
          else
            echo "Secrets are available."
          fi
